### ISSUE TITLE
Right-click on sign error

### ISSUE THREAD

**Issue by latexink** [DrakiaXYZ/Stargate-Bukkit#3]
Didn't change anything.. just started happening after a world got removed and a stargate was removed. Now I can't ineract _any_ signs.

01:29:46 [SEVERE] Could not pass event PlayerInteractEvent to Stargate
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:176)
        at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:287)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:636)
        at net.minecraft.server.Packet15Place.handle(SourceFile:39)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
        at net.TheDgtl.Stargate.Portal.activate(Portal.java:539)
        at net.TheDgtl.Stargate.Portal.cycleDestination(Portal.java:597)
        at net.TheDgtl.Stargate.Portal.cycleDestination(Portal.java:590)
        at net.TheDgtl.Stargate.Stargate$pListener.onPlayerInteract(Stargate.java:811)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        ... 12 more

**Comment by latexink** [comment]
It started workign after about 20 minutes.. just letting it sit seemed to clear it up, but would like more insight into why this happened.

**Comment by DrakiaXYZ** [comment]
I didn't take into account people removing worlds with active Stargates on them, I will fix this in the next release.

**Comment by latexink** [comment]
Yay! Thanks for this awesome plugin too.. I love it.

**Comment by DrakiaXYZ** [comment]
No problem, glad you like it :) I'm going to re open this issue until the underlying bug is resolved.

**Comment by DrakiaXYZ** [comment]
This should be fixed as of 0.7.6.7, I now reload all gates on world unload, this should stop invalid destinations from being loaded into the destination list :)
