### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Asphodan** [DrakiaXYZ/Stargate-Bukkit#9]
16:46:59 [SEVERE] Could not pass event SignChangeEvent to Stargate v0.7.9.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:26)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
        at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:1394)
        at net.minecraft.server.v1_4_R1.Packet130UpdateSign.handle(SourceFile:46)
        at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:174)
        at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
        at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
        at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:67)
        at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:600)
        at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:228)
        at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:489)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:421)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at net.TheDgtl.Stargate.LangLoader.getString(LangLoader.java:70)
        at net.TheDgtl.Stargate.Stargate.getString(Stargate.java:325)
        at net.TheDgtl.Stargate.Portal.drawSign(Portal.java:703)
        at net.TheDgtl.Stargate.Portal.createPortal(Portal.java:1150)
        at net.TheDgtl.Stargate.Stargate$bListener.onSignChange(Stargate.java:1047)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 15 more

Fresh server, no plugin conflicts that I could think of.  Happens when creating a stargate.

**Comment by DrakiaXYZ** [comment]
Note to self: Add better checks to LangLoader
